name: Auto Commit Index.html

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 (UTC 기준) 실행 (한국 시간 오전 9시 = "0 15 * * *")
  workflow_dispatch:  # 수동 실행 가능

jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Modify index.html
        run: |
          echo "<!-- Updated on $(date) -->" > index.html

      - name: Commit and Push
        run: |
          git add index.html
          git commit -m "Auto update index.html on $(date)" || echo "No changes to commit"
          git push
